### ISSUE TITLE
Late :( - Performance, Accessibility, Browser Testing

### ISSUE THREAD

**Issue by akhoinguyen** [akhoinguyen/animal-rescue-website#1]
Hi @charlie-quinn, I don't know why this completely went over my head, I forgot to tag you!! I don’t know what this will do but I decided to tag you anyway, I’m so sorry:(

**Comment by charlie-quinn** [comment]
✅ `This portion of your final assignment has been graded. A marking rubric has been sent to your gmail address.`

⚠️`Reminder: please close this issue once it has been resolved.`
